"""empty message

Revision ID: 098b4e5c4187
Revises: 429789f94a3d
Create Date: 2019-01-21 11:15:25.328812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098b4e5c4187'
down_revision = '429789f94a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture')
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ordered_at', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('order_for_maid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_for_maid'], ['maids.id'], name='orders_order_for_maid_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='orders_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='orders_pkey')
    )
    # ### end Alembic commands ###
