"""empty message

Revision ID: 429789f94a3d
Revises: 155fc4051e21
Create Date: 2019-01-20 12:46:59.957086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429789f94a3d'
down_revision = '155fc4051e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maids', sa.Column('place_to_meet', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maids', 'place_to_meet')
    # ### end Alembic commands ###
