"""empty message

Revision ID: b5e5b56705b2
Revises: 9b75f03a0494
Create Date: 2019-01-19 11:33:51.119304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e5b56705b2'
down_revision = '9b75f03a0494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_for_maid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'maids', ['order_for_maid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'order_for_maid')
    # ### end Alembic commands ###
