"""empty message

Revision ID: dae40a8037bc
Revises: b5e5b56705b2
Create Date: 2019-01-20 12:32:59.134471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae40a8037bc'
down_revision = 'b5e5b56705b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maids', sa.Column('scheduled_to_meet', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maids', 'scheduled_to_meet')
    # ### end Alembic commands ###
